# Generated by Django 5.1.1 on 2024-09-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('roles', models.CharField(choices=[('Admin', 'Admin'), ('Staffs', 'Staffs'), ('Guard', 'Guard')], max_length=50)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
            ],
        ),
    ]
